# This playbook  deploys the initial tasks such as updates, cd user set up and SSH set up
- name: setting up ansible user
  tags: ansible-user
  user:
    name: ansible
    groups: root
    shell: /bin/bash

- name: add ssh key for ansible user
  tags: ansible-user
  authorized_key:
    user: ansible
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBpAAj2EmPDnot/WYmVqK62lJ4Zi4e/dAQwSLHpkzdAD ansible"

- name: add sudoers file for ansible
  tags: ansible-user
  copy:
    src: sudoer_ansible
    dest: /etc/sudoers.d/ansible
    owner: root
    group: root
    mode: 0440
